# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LFLoginControllerExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LFLoginControllerExample
  pod 'LFLoginController'
  
  target 'LFLoginControllerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LFLoginControllerExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
